version: "3"
services:
  db:
    image: postgres:15.3
    #restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54321:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    shm_size: 1g
volumes:
  db:
    driver: local